# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'nokogiri'
gem 'rake'
gem 'rake_circle_ci', '>= 0.13.0'
gem 'rake_github'
gem 'rake_gpg', '>= 0.20.0'
gem 'rake_ssh'
gem 'rake_terraform', '>= 1.24.0'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop', '>= 1.42.0'
gem 'rubocop-rake'
gem 'rubocop-rspec', '>= 2.17.0'
gem 'semantic'
