# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awspec'
gem 'confidante'
gem 'git'
gem 'nokogiri'
gem 'rake'
gem 'rake_circle_ci', '>= 0.13.0'
gem 'rake_github', '>= 0.11.0'
gem 'rake_gpg', '>= 0.20.0'
gem 'rake_ssh', '>= 0.10.0'
gem 'rake_terraform', '>= 1.24.0'
gem 'rspec'
gem 'rspec-terraform'
gem 'rubocop'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'semantic'
